export const Users = [
    {
      id:1,
      profilePicture: "Person/1.jpg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "Person/2.jpeg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "Person/3.jpg",
      username: "Dora Hawks",
    },
    {
      id:4,
      profilePicture: "Person/4.jpg",
      username: "Harry Styles",
    },
    {
      id:5,
      profilePicture: "Person/5.jpg",
      username: "Rachel Murillo",
    },
    {
      id:6,
      profilePicture: "Person/6.jpg",
      username: "Travis Bennett",
    },
    {
      id:7,
      profilePicture: "Person/7.jpg",
      username: "Shirley Beauchamp",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "Post/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "Post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "Post/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "Post/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "Post/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "Post/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "Post/7.jpg",
      date: "2 days ago",
      userId: 1,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "Post/8.jpg",
      date: "3 days ago",
      userId: 7,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "Post/9.jpg",
      date: "5 days ago",
      userId: 5,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "Post/10.jpg",
      date: "1 week ago",
      userId: 6,
      like: 104,
      comment: 12,
    },
  ];